### ISSUE TITLE
still functional? KeyError: 'gittimestamp'

### ISSUE THREAD

**Issue by kno10** [dairiki/lektor-git-timestamp#4]
After adding the plugin, it does not show up in `lektor plugin list` and the field type causes the error `KeyError: 'gittimestamp'`

**Comment by dairiki** [comment]
It does work for me. I use it in a number of projects.

My initial thoughts on this were:
1. I do not generally install plugins the "Lektor way" (i.e. using `lektor plugins install`), but rather just install Lektor along with any desired plugins in a per-project virtualenv.
2. Perhaps when I moved the distribution metadata from setup.py/setup.cfg to pyproject.toml that broke Lektor's plugin-management and that went unnoticed by me because of thought number 1, above.

However, I've just tried to reproduce your error without success.

```
$ python -m venv venv

$ venv/bin/pip install lektor

# [typical pip spew elided]
$ venv/bin/lektor quickstart --name testing --path testing
Lektor Quickstart
=================

This wizard will generate a new basic project with some sensible defaults for
getting started quickly.  We just need to go through a few questions so that
the project is set up correctly for you.

Step 1:
| Your name.  This is used in a few places in the default template to refer to
| in the default copyright messages.
> Author Name [Jeff Dairiki]: 

Step 2:
| Do you want to generate a basic blog module?  If you enable this the models
| for a very basic blog will be generated.
> Add Basic Blog [Y/n]: 

That's all. Create project? [Y/n]

$ venv/bin/lektor --project testing plugins add lektor-git-timestamp
Package lektor-git-timestamp (0.1.post1) was added to the project

$ venv/bin/lektor --project testing plugins list
git-timestamp (version 0.1.post1)
```

I then added a `last_mod` field to `testing/models/page.ini` and a reference to it in `testing/templates/page.html` and that worked, too.

Can you give me a more specific example of how to reproduce your error?

**Comment by kno10** [comment]
I retried, and this time it worked.
I had updated the venv in the meantime (to install jinja-helpers), maybe some dependency was causing the problem.
